Changes features
vivekhit2000/Elixr-Poc01 pull request #1
Opened 2022-12-07 10:27 UTC by vivekhit2000

2022-12-09 05:34 UTC, premsrj requested changes
Requirement not clearly understood. The requirement is that both the fileName and word to be searched will be passed in as command line arguments. Not that user will be prompted for them. 

Also please rename all local variables to be proper names, now they are just two letter words.

2022-12-09 05:34 UTC, premsrj commented on src/Main.java
> +public class Main {
If this file is not needed, please remove it

2022-12-09 11:25 UTC, mh-scarmel commented on src/SearchFileApplication.java
> +            File f1 = new File(filePath);
variable name should be meaningfull name

2022-12-09 11:27 UTC, mh-scarmel commented on src/SearchingAndCountingOfWords.java
> +            BufferedReader br = new BufferedReader(fr);
why don't  use a common method for file reading part into a another class

2022-12-09 11:28 UTC, mh-scarmel commented on src/SearchFileApplication.java
> +            String storingFileContent = br.readLine();
why don't use a common method for file reading part into a another class

2022-12-12 04:49 UTC, vivekhit2000 commented on src/Main.java
> +public class Main {
Updated.

2022-12-12 04:49 UTC, vivekhit2000 commented on src/SearchFileApplication.java
> +            File f1 = new File(filePath);
Updated

2022-12-12 04:54 UTC, vivekhit2000 commented on src/SearchFileApplication.java
> +            String storingFileContent = br.readLine();
Now,I use different thing for reading the filereading part and for userinput.

2022-12-12 04:54 UTC, vivekhit2000 commented on src/SearchingAndCountingOfWords.java
> +            BufferedReader br = new BufferedReader(fr);
Now,I use different thing for reading the filereading part and for userinput.

2022-12-13 05:23 UTC, premsrj requested changes

2022-12-13 05:23 UTC, premsrj commented on src/DatabaseHelper.java
> +class DataBaseHelper {
Code seems to be completely copied from Ashutosh. Same comments I left there are applicable here as well.

2022-12-13 05:23 UTC, premsrj commented on src/SearchFileApplication.java
> +        String inputFilePath = args[0];
What happens if no arguments were passed in by the user?

2022-12-13 05:23 UTC, premsrj commented on src/SearchingAndCountingOfWords.java
> +                object.storingDataToDatabase(inputFilePath, userSearchInput, "Success", totalWordCount, " ");
You are supposed to save the number of times the searched word repeats, not the number of words in the file.

2022-12-13 05:23 UTC, premsrj commented on src/SearchFileApplication.java
> +            String storingFileContent = Files.readAllLines(filepath).get(0);
You need to validate if the file is actually a json or txt file

2022-12-13 08:35 UTC, vivekhit2000 commented on src/SearchingAndCountingOfWords.java
> +                object.storingDataToDatabase(inputFilePath, userSearchInput, "Success", totalWordCount, " ");
updated.

2022-12-14 07:31 UTC, charanvelury requested changes
Please work on the comments

2022-12-14 07:31 UTC, charanvelury commented on src/DatabaseHelper.java
> +            connectionToDataBase = DriverManager.getConnection(this.mySqlUrl, this.userName, this.passwordOfDatabase);
Put these two lines into a single method called "getConnection(.., ..)" that returns connection object so that you can use this method in place of these two lines wherever table querying need arises.

2022-12-14 07:38 UTC, vivekhit2000 commented on src/DatabaseHelper.java
> +            connectionToDataBase = DriverManager.getConnection(this.mySqlUrl, this.userName, this.passwordOfDatabase);
Sometimes it not required to load driver class manually. The driver class loads automatically by itself. There I am creating connection to database just to check whether the table is present or not

2022-12-14 12:03 UTC, mh-scarmel approved these changes

2022-12-22 09:26 UTC, mh-scarmel commented on src/SearchFileApplication.java
> +        if (args.length == Constants.argumentlength) {
In constant class you added a variable ARGUMENT_LENGTH but here using Constants.argumentlength

2022-12-22 09:35 UTC, vivekhit2000 commented on src/SearchFileApplication.java
> +        if (args.length == Constants.argumentlength) {
updated.

2022-12-22 09:57 UTC, mh-scarmel commented on src/SearchingAndCountingOfWords.java
> +        if (inputFilePath.endsWith("txt") || inputFilePath.endsWith("json")) {
move the extensions to constant class

2022-12-22 10:02 UTC, vivekhit2000 commented on src/SearchingAndCountingOfWords.java
> +        if (inputFilePath.endsWith("txt") || inputFilePath.endsWith("json")) {
update

2022-12-22 10:05 UTC, mh-scarmel commented on src/SearchingAndCountingOfWords.java
> +
remove below extra lines

2022-12-22 11:22 UTC, vivekhit2000 commented on src/SearchingAndCountingOfWords.java
> +
removed.

2022-12-22 11:28 UTC, mh-scarmel approved these changes

2022-12-26 05:02 UTC, mh-saicharanvelury commented on src/DatabaseHelper.java
> +            ResultSet tables = checkIfTableIsThere.getTables(null, null, "audit", null);
Please declare this table name "audit" in Constants class and take it from constants as the table name may not change frequently

2022-12-26 05:03 UTC, mh-saicharanvelury commented on src/DatabaseHelper.java
> +            String query = MessageFormat.format("INSERT INTO audit VALUES ({0},{1},{2},{3},{4},{5})", "'" + pathOfTheFile + "'", "'" + userSearchedWord + "'", "'" + currentDateAndTime + "'", "'" + re
Follow my earlier comment on taking audit to constants class and accessing it from there

2022-12-26 05:04 UTC, mh-saicharanvelury commented on src/SearchingAndCountingOfWords.java
> +                words = inputForSplit.split("[.,!@#$%*()=/;:+_ ]");
Make ".,!@#$%*()=/;:+_ ]" as variable in constants class and access it from tehre

2022-12-26 05:07 UTC, mh-saicharanvelury commented on src/SearchingAndCountingOfWords.java
> +            while ((inputForSplit = br.readLine()) != null) {
For looping through lines and searching for words, StringTokenizer class may be more appropriate as that class is meamt for that. However I will leave this as optional comment

2022-12-26 05:10 UTC, mh-saicharanvelury requested changes
Added a few comments

2022-12-26 05:38 UTC, vivekhit2000 commented on src/SearchingAndCountingOfWords.java
> +            while ((inputForSplit = br.readLine()) != null) {
As i am not familiar with this, and due to shortage of time, for time being I left as it is.

2022-12-26 05:38 UTC, vivekhit2000 commented on src/SearchingAndCountingOfWords.java
> +                words = inputForSplit.split("[.,!@#$%*()=/;:+_ ]");
Resolved

2022-12-26 05:39 UTC, vivekhit2000 commented on src/DatabaseHelper.java
> +            ResultSet tables = checkIfTableIsThere.getTables(null, null, "audit", null);
Resolved

2022-12-27 06:00 UTC, mh-ppremlatha requested changes

2022-12-27 06:00 UTC, mh-ppremlatha commented on src/SearchFileApplication.java
> +
Remove all of these extra empty lines

2022-12-27 06:00 UTC, mh-ppremlatha commented on src/SearchingAndCountingOfWords.java
> +class SearchingAndCountingOfWords implements Callable<Integer> {
File is not properly formatted. Leave an empty line before the start of every method.

2022-12-27 06:42 UTC, vivekhit2000 commented on src/DatabaseHelper.java
> +            String query = MessageFormat.format("INSERT INTO audit VALUES ({0},{1},{2},{3},{4},{5})", "'" + pathOfTheFile + "'", "'" + userSearchedWord + "'", "'" + currentDateAndTime + "'", "'" + re
updated

2022-12-27 06:43 UTC, vivekhit2000 commented on src/SearchingAndCountingOfWords.java
> +class SearchingAndCountingOfWords implements Callable<Integer> {
updated

2022-12-27 06:43 UTC, vivekhit2000 commented on src/SearchFileApplication.java
> +
updated

2022-12-27 06:56 UTC, mh-saicharanvelury commented on src/SearchFileApplication.java
> +}
Try leaving a single line at the end of this file and see whether this - minus symbol goes away. If it is success, then repeat the same for other files where - symbol appears

2022-12-27 06:56 UTC, mh-saicharanvelury requested changes
- symbol

2022-12-27 07:10 UTC, vivekhit2000 commented on src/SearchFileApplication.java
> +}
ok

2022-12-27 09:45 UTC, mh-ppremlatha approved these changes

2023-01-18 14:58 UTC, merged